### PR TITLE
added wuppertal

### PR DESCRIPTION
**Pull request by exmatrikulator**

### CODE REVIEW

**Comment by tursics** [comment]
Superb! Only one question left: Did the background image has a copyright info?
 app/wuppertal/background.jpg

**Comment by exmatrikulator** [comment]
it's my own work. (cc)

**Comment by derhuerst** [comment]
There are typos in [`app/wuppertal/schwebabhn.json`](https://github.com/tursics/data-dashboard/blob/e414f10/app/wuppertal/schwebabhn.json) on [line 8](https://github.com/tursics/data-dashboard/blob/e414f10/app/wuppertal/schwebabhn.json#L8), [line 18](https://github.com/tursics/data-dashboard/blob/e414f10/app/wuppertal/schwebabhn.json#L18) and in the file name.

**Comment by exmatrikulator** [comment]
uh ha, thanks!

**Pull request merged**
